# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google play Beta"
  lane :beta do

  #increment Version
  increment_version_code
  commit_android_version_bump(force:true)
  push_to_git_remote

  #build
    gradle(
        task: 'assemble',
        build_type: 'Release'
      )

  #release notes
  changelog_from_git_commits

  #upload
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

